[build]
  command = "npm run build:client"
  publish = "dist/spa"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/send-verification-code"
  to = "/.netlify/functions/send-verification-code"
  status = 200

[[redirects]]
  from = "/api/quote-estimate"
  to = "/.netlify/functions/quote-estimate"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
